version: '2' 
services:
    node:
      build:
        context: .
	dockerfile: Dockerfile_nodejs
      ports:
        - "3000:3000"
      networks:
	- nodeapp-network 
    mongodb:
      image: mongo
      networks:
	- nodeapp-network
networks:
  nodeapp-network:
    driver: bridge
